channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.0
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==23.2
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
name: mlflow-env
